// 주문 상태
export const ORDER_STATUS = {
  PENDING: '주문대기',
  COMPLETED: '주문완료',
  INTERNATIONAL_SHIPPING: '해외배송중',
  WAREHOUSE_PROCESSING: '입고처리',
  SHIPPING: '배송중',
  DELIVERED: '배송완료'
};

export const ORDER_STATUS_COLORS = {
  [ORDER_STATUS.PENDING]: '#faad14',
  [ORDER_STATUS.COMPLETED]: '#52c41a',
  [ORDER_STATUS.INTERNATIONAL_SHIPPING]: '#1890ff',
  [ORDER_STATUS.WAREHOUSE_PROCESSING]: '#722ed1',
  [ORDER_STATUS.SHIPPING]: '#13c2c2',
  [ORDER_STATUS.DELIVERED]: '#52c41a'
};

